# Generated by Django 4.0.4 on 2022-08-30 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCUG', '0004_alter_private_message_from_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_activity',
            new_name='last_active',
        ),
        migrations.RemoveField(
            model_name='private_message',
            name='content',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='comment',
            name='ip_owner',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='forum',
            name='title',
            field=models.CharField(default='Null', max_length=64),
        ),
        migrations.AddField(
            model_name='post',
            name='ip_owner',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Null', max_length=64),
        ),
        migrations.AddField(
            model_name='private_message',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
