# Generated by Django 3.2.9 on 2022-09-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCUG', '0006_auto_20220915_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='/static/icons/profile_white.png', upload_to='uploaded', verbose_name='picture'),
        ),
    ]
