# Generated by Django 3.2.9 on 2022-09-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCUG', '0010_auto_20220925_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='uploaded', verbose_name='picture'),
        ),
    ]
