# Generated by Django 3.2.9 on 2022-09-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCUG', '0011_auto_20220925_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/static/images/nfg.png', upload_to='profile_pics', verbose_name='picture'),
        ),
    ]
