# Generated by Django 3.2.9 on 2022-09-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCUG', '0012_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/static/images/nft.png', upload_to='profile_pics', verbose_name='picture'),
        ),
    ]
