# Generated by Django 4.1.1 on 2022-09-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCUG', '0013_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='nft.png', upload_to='profile_pics', verbose_name='picture'),
        ),
    ]
