# Generated by Django 4.1.1 on 2022-09-27 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UCUG', '0015_alter_user_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
