# Generated by Django 4.1.1 on 2022-11-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCUG', '0019_session_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='message',
            field=models.CharField(choices=[('NONE', ''), ('NO_AUTH', 'NO_AUTH')], default='NONE', max_length=16),
        ),
    ]
