# Generated by Django 4.1.1 on 2022-11-04 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_UTC', models.DateTimeField(auto_now_add=True)),
                ('updated_UTC', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Null', max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Null', max_length=64)),
                ('content', models.TextField()),
                ('created_UTC', models.DateTimeField(auto_now_add=True)),
                ('updated_UTC', models.DateTimeField(auto_now=True)),
                ('ip_owner', models.GenericIPAddressField(null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent_forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucug_forum.forum')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_UTC', models.DateTimeField(auto_now_add=True)),
                ('updated_UTC', models.DateTimeField(auto_now=True)),
                ('ip_owner', models.GenericIPAddressField(null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ucug_forum.comment')),
                ('parent_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ucug_forum.post')),
            ],
        ),
    ]
