# Generated by Django 3.2.9 on 2022-12-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucug_forum', '0004_alter_post_mentions'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reply_count',
            field=models.SmallIntegerField(default=0),
        ),
    ]
