# Generated by Django 4.1.1 on 2022-12-10 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ucug_forum', '0006_alter_forum_description_alter_forum_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('user', models.IntegerField(primary_key=True, serialize=False)),
                ('post', models.IntegerField()),
                ('created_UTC', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('user', 'post')},
            },
        ),
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='mentions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_mention', to='ucug_forum.post'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
