# Generated by Django 4.1.1 on 2022-12-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucug_forum', '0007_like_post_like_count_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='created_UTC',
            field=models.DateTimeField(),
        ),
    ]
