# Generated by Django 4.1.1 on 2022-12-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucug_forum', '0009_alter_like_created_utc'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='like',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='user_post_pair'),
        ),
    ]
